/*
 * Video Game Database - Test Application
 * https://github.com/TechieTester/VideoGameDB
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 4.3.1
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "/app";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/videogames", () => {
        let url = BASE_URL + `/videogames`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "successful operation": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);

        // Request No. 2
        // TODO: edit the parameters of the request body.
        body = {"id": "integer", "name": "string", "releaseDate": "date", "reviewScore": "integer", "category": "string", "rating": "string"};
        params = {headers: {"Content-Type": "application/xml"}};
        request = http.post(url, body, params);
        check(request, {
            "successful operation": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
    group("/videogames/{videoGameId}", () => {
        let videoGameId = "TODO_EDIT_THE_VIDEOGAMEID";
        let url = BASE_URL + `/videogames/${videoGameId}`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "successful operation": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);

        // Request No. 2
        // TODO: edit the parameters of the request body.
        body = {"id": "integer", "name": "string", "releaseDate": "date", "reviewScore": "integer", "category": "string", "rating": "string"};
        params = {headers: {"Content-Type": "application/xml"}};
        request = http.put(url, body, params);
        check(request, {
            "successful operation": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);

        // Request No. 3
        request = http.delete(url);
        check(request, {
            "successful operation": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
}
